export enum CustomStatusCodes {
  DB_ERROR = "DB_ERROR",
  USER_LOGGED_OUT = "USER_LOGGED_OUT",
  ROUTE_NOT_EXISTS = "ROUTE_NOT_EXISTS",
  INVALID_PASSWORD = "INVALID_PASSWORD",
  USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",
  USER_DOES_NOT_EXIST = "USER_DOES_NOT_EXIST",
  INVALID_LOGIN_METHOD = "INVALID_LOGIN_METHOD",
  USER_FAILED_TO_CREATE = "USER_FAILED_TO_CREATE",
  USER_SUCCESSFULLY_CREATED = "USER_SUCCESSFULLY_CREATED",
}
