export enum CustomStatusCodes {
  DB_ERROR = "DB_ERROR",
  ROUTE_NOT_EXISTS = "ROUTE_NOT_EXISTS",

  INVALID_PASSWORD = "INVALID_PASSWORD",

  INVALID_LOGIN_METHOD = "INVALID_LOGIN_METHOD",

  PASSWORD_RESET_TOKEN_FAILED_TO_CREATE = "PASSWORD_RESET_TOKEN_FAILED_TO_CREATE",

  INVALID_TOKEN = "INVALID_TOKEN",

  USER_LOGGED_OUT = "USER_LOGGED_OUT",
  USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",
  USER_DOES_NOT_EXIST = "USER_DOES_NOT_EXIST",
  USER_FAILED_TO_CREATE = "USER_FAILED_TO_CREATE",
  USER_SUCCESSFULLY_CREATED = "USER_SUCCESSFULLY_CREATED",
}
