name: Git

on:
  workflow_call: {}

jobs:
  runner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # GitVersion needs full history

      - name: Setup GitVersion
        uses: GitTools/actions/gitversion/setup@v3
        with:
          versionSpec: "5.x"

      - name: Run GitVersion
        id: gitversion
        uses: GitTools/actions/gitversion/execute@v3
        with:
          useConfigFile: true
          configFilePath: GitVersion.yml

      - name: Save git tags to artifact
        id: gittag
        run: |
          echo "SEMVER=${{ env.GitVersion_SemVer }}" >> build.env
          echo "FULL_SEMVER=${{ env.GitVersion_FullSemVer }}" >> build.env
          echo "BRANCH=${{ env.GitVersion_BranchName }}" >> build.env

          echo "Debugging..."
          echo "SEMVER = ${{ env.GitVersion_SemVer }}"
          echo "FULL_SEMVER = ${{ env.GitVersion_FullSemVer }}"
          echo "BRANCH = ${{ env.GitVersion_BranchName }}"

      - name: Upload version artifact
        uses: actions/upload-artifact@v4
        with:
          name: version
          path: build.env
