name: Git

on:
  workflow_call: {}

jobs:
  runner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref || github.ref }}

      - name: Setup GitVersion
        uses: GitTools/actions/gitversion/setup@v3
        with:
          versionSpec: "5.x"

      - name: Run GitVersion
        id: gitversion
        uses: GitTools/actions/gitversion/execute@v3
        with:
          useConfigFile: true
          configFilePath: GitVersion.yml

      - name: Save git tags to artifact
        id: gittag
        run: |
          GIT_EVENT="${{ github.event_name }}"
          BRANCH="${{ env.GitVersion_BranchName }}"

          if [ "$GIT_EVENT" = "pull_request" ]; then

            echo "Detected PR build"

            CLEAN_BRANCH="${{ github.head_ref }}"
            CLEAN_BRANCH=$(echo "$CLEAN_BRANCH" | sed 's#[^a-zA-Z0-9._-]#-#g')
            SEMVER="${{ env.GitVersion_Major }}.${{ env.GitVersion_Minor }}.${{ env.GitVersion_Patch }}-${CLEAN_BRANCH}.${{ env.GitVersion_CommitsSinceVersionSource }}"

          elif [ "$BRANCH" = "master" ]; then

            echo "Master branch detected"

            SEMVER="${{ env.GitVersion_SemVer }}"

          else  

            echo "Feature/Hotfix branch detected"

            FULL_SEMVER="${{ env.GitVersion_FullSemVer }}"
            COMMIT_NUMBER=${{ env.GitVersion_CommitsSinceVersionSource }}

            # Replace ".<number>+<commits>" with ".<commits>"
            SEMVER=$(echo "$FULL_SEMVER" | sed -E "s/\.[0-9]+\+([0-9]+)/.\1/")

          fi

          echo "SEMVER=$SEMVER" >> build.env

      - name: Upload version artifact
        uses: actions/upload-artifact@v4
        with:
          name: tags
          path: build.env
