name: Main

on:
  push:
    branches:
      - master
      - "feat/*"
      - "fix/*"
      - "hotfix/*"

jobs:
  git:
    uses: ./.github/workflows/git.yml

  build:
    needs: git
    uses: ./.github/workflows/build.yml

  release:
    runs-on: ubuntu-latest
    needs: [git, build]
    # uses: ./.github/workflows/release.yml
    steps:
      - name: test
        run: echo $needs.git.outputs
    # env:
    #   git-tag: ${{ needs.git.outputs.git-tag }}
