name: Main

on:
  push:
    branches:
      - master
      - "feat/*"
      - "fix/*"
      - "hotfix/*"

jobs:
  git:
    uses: ./.github/workflows/git.yml

  build:
    needs: git
    uses: ./.github/workflows/build.yml

  debug:
    needs: [git, build]
    runs-on: ubuntu-latest
    steps:
      - name: Show all needs context
        run: echo '${{ toJSON(needs) }}'

      - name: Show only git outputs
        run: echo '${{ toJSON(needs.git.outputs) }}'

      - name: Show git-tag specifically
        run: echo "git-tag=${{ needs.git.outputs.git-tag }}"

  release:
    needs: [git, build]
    uses: ./.github/workflows/release.yml
    with:
      git-tag: ${{ needs.git.outputs.git-tag }}
