name: Main

on:
  push:
    branches:
      - master
      - "feat/*"
      - "fix/*"
      - "hotfix/*"

jobs:
  git:
    uses: ./.github/workflows/git.yml

  build:
    needs: git
    uses: ./.github/workflows/build.yml

  release:
    # runs-on: ubuntu-latest
    needs: [git, build]
    uses: ./.github/workflows/release.yml
    with:
      git-tag: ${{ steps.build_version.outputs.git-tag }}
    # steps:
    #   - name: Show all needs
    #     run: echo '${{ toJSON(needs) }}'
