name: CI Pipeline

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

permissions:
  contents: write

jobs:
  git:
    if: github.event_name == 'pull_request' || (github.event_name == 'push' && github.event.pull_request == null)
    uses: ./.github/workflows/git.yml

  build:
    needs: git
    uses: ./.github/workflows/build.yml

  release:
    needs: [git, build]
    uses: ./.github/workflows/release.yml
