name: CI Pipeline

on:
  push:
    branches:
      - master
      - "feat/*"
      - "fix/*"
      - "hotfix/*"

env:
  GIT_TAG: ""

jobs:
  git:
    uses: ./.github/workflows/git.yml

  debug:
    runs-on: ubuntu-latest
    needs: git
    steps:
      - name: Show all needs context
        run: echo '${{ toJSON(needs) }}'

      - name: Show git job outputs
        run: echo '${{ toJSON(needs.git.outputs) }}'

      - name: Show SemVer explicitly
        run: echo "SemVer = ${{ env.GitVersion_SemVer }}"

      - name: Show FullSemVer explicitly
        run: echo "FullSemVer = ${{ env.GitVersion_FullSemVer }}"

  build:
    needs: git
    uses: ./.github/workflows/build.yml

  release:
    needs: [git, build]
    uses: ./.github/workflows/release.yml
