name: Release

on:
  push:
    branches:
      - master
      - "feat/*"
      - "fix/*"
      - "hotfix/*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # GitVersion needs full history

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm i -g pnpm && pnpm install --frozen-lockfile

      - name: Run GitVersion
        id: gitversion
        uses: GitTools/actions/gitversion/execute@v0.10.2
        with:
          useConfigFile: true

      - name: Update package.json version
        run: |
          VERSION=${{ steps.gitversion.outputs.semVer }}
          echo "Using version $VERSION"
          npm version $VERSION --no-git-tag-version

      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
